### ISSUE TITLE
Jupytext instead of ipynb?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari.github.io#109]
How do people feel about using [jupytext frontmatter and markdown](https://jupyterbook.org/file-types/myst-notebooks.html?highlight=jupytext) format instead of checking in `ipynb` files?  It makes version control much easier to parse, and it's easier to look at files on github (I know that ipynb eventually renders on github ... but it's slow and buggy).

many examples of jupytext usage can be found in the [jupyter-book docs](https://github.com/executablebooks/jupyter-book/blob/master/docs/file-types/myst-notebooks.md), and the recent [magicgui doc in napari](https://github.com/napari/napari/blob/master/docs/guides/magicgui.md) uses it too

**Comment by GenevieveBuckley** [comment]
I'm going to say I don't like the idea, for all the same reasons as the last time we discussed it.

* I want people (new users) to be able to download or clone this repository and then immediately be able to play around with the tutorials directly.
* When people write new tutorials to contribute to the tutorials repository, they're generally going to write the example in a notebook first, and I don't think it's reasonable to force them to do extra steps here before making a PR. (I believe people will have good intentions about getting around to it... eventually, but that's going to have a chilling effect on new contributions regardless.)
* I want us to move some of the webinar content over into the tutorials repository, and that's also written in notebooks too.

Addressing your objections:
* We'd decided to use ReviewNB to handle the problem of ugly notebook diffs in version control https://www.reviewnb.com/
* I don't really understand why you'd often be looking at the .ipynb files on github, if the lag in rendering the html bothers you why not just look at the already rendered html pages at https://napari.org/tutorials/? Merged PRs are published almost instantly, so it's never out of date or anything.

Does that help?

**Comment by GenevieveBuckley** [comment]
I also want to link to nbQA (https://github.com/nbQA-dev/nbQA) which is a suite of tools you can use to add pre-commit hooks to jupyter notebooks (it includes tools like black, isort, mypy).

**Comment by jni** [comment]
@GenevieveBuckley I really don't think the objections are insurmountable. We just need people to pip install jupytext and install the pre-commit hook here:

https://jupytext.readthedocs.io/en/latest/using-pre-commit.html

Also note that jupytext lets you autosave a notebook as any of their supported formats *from the notebook menu itself*, see here:

https://jupytext.readthedocs.io/en/latest/install.html#jupytext-menu-in-jupyter-notebook

When you open a jupytext .py in ipynb, it automatically is opened as a notebook if you have jupytext installed:

https://jupytext.readthedocs.io/en/latest/faq.html#which-files-should-i-version-control

My vote is definitely for a jupytext format, probably myst, since the rest of our docs are in myst. Jupytext also makes it much easier to do quick fixes on the docs in which you don't touch the code. I don't want to have to launch a notebook to do that.

**Comment by tlambert03** [comment]
(whoops):

> I want people (new users) to be able to download or clone this repository and then immediately be able to play around with the tutorials directly.

that is a nice goal, but I agree with juan that writing them in ipynb is not the only way to achieve that.   Note, for example, the buttons on the top right of [this page](https://jupyterbook.org/file-types/myst-notebooks.html?highlight=jupytext) in the jupyter-book docs.  You can immediately download the file as ipynb (which I would argue is easier than cloning a repository for a beginner).   You can also immediately launch the file in binder (if we can get napari to support that).  In other words, there are definitely quick paths to get newcomers to be able to run the code, short of having them clone a bunch of notebooks (which are scattered about some folders with non-notebook files).

> When people write new tutorials to contribute to the tutorials repository, they're generally going to write the example in a notebook first, and I don't think it's reasonable to force them to do extra steps here before making a PR. (I believe people will have good intentions about getting around to it... eventually, but that's going to have a chilling effect on new contributions regardless.)

I respect that perspective (that people are generally going to write things in a notebook first) ... but I don't think I share it.  I personally find it to be an extra hassle to get the notebook server up and running, and always write in markdown.  I'm not saying that everyone does that, but I am saying that not everyone is going to write in a notebook first.   There's a diversity of contributors.

> I want us to move some of the webinar content over into the tutorials repository, and that's also written in notebooks too.

that seems kinda like a separate point. anything can be converted either way (for instance, you converted all the markdown to ipynb... it can also go the other way)

**Comment by GenevieveBuckley** [comment]
> > I want people (new users) to be able to download or clone this repository and then immediately be able to play around with the tutorials directly.
> 
> that is a nice goal, but I agree with juan that writing them in ipynb is not the only way to achieve that. Note, for example, the buttons on the top right of [this page](https://jupyterbook.org/file-types/myst-notebooks.html?highlight=jupytext) in the jupyter-book docs. You can immediately download the file as ipynb (which I would argue is easier than cloning a repository for a beginner). You can also immediately launch the file in binder (if we can get napari to support that). 

I'd be fine with something like that.
Binder would also be nice, if it's not super slow (from memory, Juan & Nick got it working for the first NUBIAS workshop, but performance was an issue).

> > When people write new tutorials to contribute to the tutorials repository, they're generally going to write the example in a notebook first, and I don't think it's reasonable to force them to do extra steps here before making a PR. (I believe people will have good intentions about getting around to it... eventually, but that's going to have a chilling effect on new contributions regardless.)
> 
> I respect that perspective (that people are generally going to write things in a notebook first) ... but I don't think I share it. I personally find it to be an extra hassle to get the notebook server up and running, and always write in markdown. I'm not saying that everyone does that, but I am saying that not everyone is going to write in a notebook first. There's a diversity of contributors.

I mean, you can keep writing markdown, it renders just fine. The problem with that currently is that those don't get executed & so it's too easy for a typo or API mismatch to creep in there (especially as time goes on).

> > I want us to move some of the webinar content over into the tutorials repository, and that's also written in notebooks too.
> 
> that seems kinda like a separate point. anything can be converted either way (for instance, you converted all the markdown to ipynb... it can also go the other way)

No, I want us to *stop* spending all this effort converting things for different purposes. Whatever people are writing in originally, is the format we should stick with, imo.

**Comment by tlambert03** [comment]
> The problem with that currently is that those don't get executed & so it's too easy for a typo or API mismatch to creep in there (especially as time goes on).

they _do_ get executed! that's the point.  The images on this page are all dynamically rendered (and would fail if there was API mistmatch): https://napari.org/docs/dev/guides/magicgui.html

**Comment by GenevieveBuckley** [comment]
> > The problem with that currently is that those don't get executed & so it's too easy for a typo or API mismatch to creep in there (especially as time goes on).
> 
> they _do_ get executed! that's the point. The images on this page are all dynamically rendered (and would fail if there was API mistmatch): https://napari.org/docs/dev/guides/magicgui.html

... you mean, if we use jupytext they will get executed. Right now, nothing in markdown is checked.

**Comment by tlambert03** [comment]
> if we use jupytext they will get executed.

correct.

**Comment by GenevieveBuckley** [comment]
In summary:
1. I want executed docs
2. That can be easily downloaded as notebooks
3. That people can submit already created notebook tutorials to
4. And that we do not need to spend time & effort converting between different formats

**Comment by GenevieveBuckley** [comment]
TBH I don't really care what solution we actually choose, I just want those four things.
Edit: I think I also value whatever it is being the simplest possible solution, again because this needs to be easy to use & we are spending too much time and effort right now.

**Comment by tlambert03** [comment]
> I want executed docs

✅ absolutely.  deal breaker otherwise

> That can be easily downloaded as notebooks

✅ yep.  the download link at the top right of [this page](https://jupyterbook.org/file-types/myst-notebooks.html?highlight=jupytext) does it for me... how about you? 

> That people can submit already created notebook tutorials to

✅ that's fine!  I'm not so much asserting what everyone every _must_ do to contribute to these repos... more just what maybe the core devs are encouraged to do maybe? From the perspective of us, internally, trying to say "what do our tutorials say, what _have_ they said, and how has it changed over time"... the version control on jupytext is _way_ better.

> And that we do not need to spend time & effort converting between different formats

this is a one-time conversation.  I don't expect we'll need to go back and forth.  I just failed to notice that everything got converted to ipynb until now... was just trying to figure out the history of a page, and that's why I posted this... :)

**Comment by GenevieveBuckley** [comment]
> From the perspective of us, internally, trying to say "what do our tutorials say, what have they said, and how has it changed over time"... the version control on jupytext is way better.

Well, that's a plus!

> was just trying to figure out the history of a page, and that's why I posted this... :)

Uh yeah, I did not try to preserve any history in the conversion. I'm pretty sure there wasn't a great deal to note, especially for the fundamentals tutorials (I'd expect this to be more important for the applications - then you really want to know who wrote what & when).

**Comment by GenevieveBuckley** [comment]
When I click the jupytext download button in the top right hand corner, this window with the json opens. There *is* a "Save" button in the top left corner, and when you click that *then* it does actually download. 

So not really the most straightforward, but it does do the thing.

![2021-03-02-jupytext-download](https://user-images.githubusercontent.com/30920819/109586859-2a301780-7b5a-11eb-8a38-10e8432e2d2a.png)

**Comment by tlambert03** [comment]
yeah, the firefox json parser does make it a little confusing doesn't it.  We could probably edit html that creates that link to make it immediately download (i.e. the right click "save as" behavior)

**Comment by jni** [comment]
Yeah, all of the browsers I've tried (FF, Chrome, Safari) render the JSON instead of downloading it. right-click -> save as on the link works. @GenevieveBuckley it doesn't seem that this is a jupytext thing but a browser thing.

**Comment by tlambert03** [comment]
Yep, and we can solve that using the download tag property: https://www.w3schools.com/tags/att_a_download.asp

**Comment by GenevieveBuckley** [comment]
Ok, so for implementing this we'd probably want to make changes on top of [this point in the git commit history](https://github.com/napari/tutorials/commit/504f81d11567fac7ff3cc882b66c77c03b7a0644) (and add the link reformatting from [#108](https://github.com/napari/tutorials/pull/108/files), which was something I missed when changing the rest of the links).

+1 to using the [download tag property](https://www.w3schools.com/tags/att_a_download.asp)
