### ISSUE TITLE
Remove notebook error caused by comment following ipython magic

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari.github.io#113]
We want to remove this notebook error.

![2021-03-02-napari-tutorials-invalid-gui-request](https://user-images.githubusercontent.com/30920819/109587157-b04c5e00-7b5a-11eb-94bc-28334f2b716c.png)

I think it's caused by the comment immediately following ipython magic. We could try to either:
1. Put the comment on a line by itself, before the `%gui qt` magic, OR
2. Put text of the commend into a markdown cell (I do think we need to explain why this magic is there)

**Comment by GenevieveBuckley** [comment]
I was trying a fix in https://github.com/napari/tutorials/pull/110 but the CI tests are failing, so we'll have to resolve that problem first

**Comment by tlambert03** [comment]
Also just want to point out... you don't technically need it there at all (except for possible educational purposes).  But I don't think you need to actually execute it (so it could be in a pure markdown cell)

**Comment by GenevieveBuckley** [comment]
I think the educational purposes are pretty important! Especially if [this is no longer a thing](https://github.com/napari/napari/issues/2233).

**Comment by jni** [comment]
@GenevieveBuckley I think @tlambert03's point is that the string is not exactly accurate — we *don't* have to start the event loop before import. We *probably should* start it before making a viewer, and we *must* (I think? @tlambert03?) start it before the `nbscreenshot`.

So yeah, educational purposes are absolutely critical, we should just make sure we educate correctly — the issue you link to shows that we had a lot of muddled ideas about event loops in napari before, and now that we are sorting them out, we risk confusing a lot of the community.

**Comment by tlambert03** [comment]
yep, definitely wasn't trying to diminish the educational purpose.  was just trying to point out that, in the context of removing the error (what this post was about), you can just not execute that cell at all and you'll be fine.  by "not execute" I don't mean to imply that you need to delete it... that's what I meant by put it in a  "pure markdown cell": in other words, let it be part of the narrative if you want to, but if the error you're getting by executing that cell is causing you grief, just don't execute it.

It's _only_ necessary if you want to have an interactive IPython session (which you are not doing here).

> we don't have to start the event loop before import. 

correct

> We probably should start it before making a viewer

totally optional.  you can call `%gui qt` _after_ making a viewer too and it will show a viewer and not block...

> and we must (I think? @tlambert03?) start it before the nbscreenshot.

nope actually. not necessary there either. nbscreenshot will [processEvents for you](https://github.com/napari/napari/pull/2303)... (this was actually necessary otherwise you'd have [no layer list in the viewer](https://github.com/napari/napari/issues/1596))

so, to be clear: you can completely remove `%gui qt` here and the _docs_ will be fine.  I know I keep referring to it, but have a look at the [recent magicgui docs in napari](https://github.com/napari/napari/blob/master/docs/guides/magicgui.md), where I do just that.  again, I'm not saying that you should remove all mention of `%gui qt`... but you don't need to execute it.

**Comment by tlambert03** [comment]
side note: should we have a short zoom session sometime (with anyone interested) to talk about all the confusing Qt things?

**Comment by jni** [comment]
> nbscreenshot will processEvents for you...

My mind is suitably blown.

> should we have a short zoom session sometime (with anyone interested) to talk about all the confusing Qt things?

Yes, probably, plus update the [event loop doc](https://napari.org/docs/dev/guides/event_loop.html), and e.g. link to it when people use `napari.gui_qt()`.

**Comment by tlambert03** [comment]
> My mind is suitably blown.

not to hijack the thread, but here's another revelation:

```python
from qtpy.QtWidgets import QApplication, QPushButton

app = QApplication([])

button = QPushButton("Push Me")
button.clicked.connect(lambda e: print("clicked!"))
button.show()  # obviously, not shown yet

app.processEvents()  # now you see the button
# buuuuut.... try to click on it.
# it appears that the app has crashed... spinning pinwheel of death

app.processEvents()  # 🤯  (prints "clicked!")

app.exec_()  # click to your heart's content
# then close the window 
# (by default Qt quits the event loop when the last window is gone)

# make a new one
button2 = QPushButton("Push Me2")
button2.clicked.connect(lambda e: print("clicked2!"))
button2.show()  # not shown yet

# go nuts
%gui qt
```

so, %gui qt, and `app.exec_()` are just glorified versions of:
```python
while True:
    app.processEvents()
```

**Comment by GenevieveBuckley** [comment]
> @GenevieveBuckley I think @tlambert03's point is that the string is not exactly accurate — we _don't_ have to start the event loop before import. We _probably should_ start it before making a viewer, and we _must_ (I think? @tlambert03?) start it before the `nbscreenshot`.

Ooooh, I see. So we're not arguing about whether there should be an explanation included, it's that the content I've written is incorrect. That's fine, we should replace that with something that *is* correct. (Which probably means Talley will need to write it, since he understands it best)

**Comment by GenevieveBuckley** [comment]
> so, to be clear: you can completely remove %gui qt here and the docs will be fine. I know I keep referring to it, but have a look at the recent magicgui docs in napari, where I do just that. again, I'm not saying that you should remove all mention of %gui qt... but you don't need to execute it.

But if we remove it and a new user downloads the notebook, they will not be able to run it properly (assuming they launch jupyter with the usual `jupyter notebook` command).

I care way less about whether it's strictly necessary to build the docs, and much more about whether we're showing people the same way we expect them to use napari most often.

**Comment by jni** [comment]
Yeah, we probably don't need to remove it, but we can e.g. have a link out to the updated docs which should explain everything we just discussed.

**Comment by tlambert03** [comment]
> But if we remove it and a new user downloads the notebook, they will not be able to run it properly (assuming they launch jupyter with the usual jupyter notebook command).

Not quite: if it runs while building the docs, it will run as an independent ipython notebook. (That’s one of the whole points we all agree is nice about using Jupyter book here).

I’m sorry I’m having difficulty explaining this here. I certainly wasn’t saying to remove it. I was just trying to offer an option for removing the error that opened this post.  We can have the discussion about how best to present this to users somewhere else

**Comment by jni** [comment]
> Not quite: if it runs while building the docs, it will run as an independent ipython notebook. (That’s one of the whole points we all agree is nice about using Jupyter book here).

@tlambert03 yeah but we'll do stuff like create the viewer, fix the camera settings, (nothing happens), then call nbscreenshot, which will create a viewer window that instantly becomes non-responsive, right? That's not super great user experience for that notebook! :joy:

**Comment by tlambert03** [comment]
Ok, to summarize: leave in the gui qt, explain why it’s there.  If you’d like to (but you don’t have to!!) you can comment it out and tell people to uncomment it.  I’ll open an issue elsewhere where we can discuss how we can simplify this

**Comment by GenevieveBuckley** [comment]
Given https://github.com/napari/napari/pull/2406 we can probably get rid of the `%gui qt` stuff entirely (starting from napari version 0.4.7)
