### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari.github.io#129]
Our continuous integration checks are failing (noticed on a recent PR that made no code changes, just updated the user instructions https://github.com/napari/napari.github.io/pull/128).

[The logs](https://github.com/napari/napari.github.io/pull/128/checks?check_run_id=2557994581) seem to suggest that a flaky X11 connection is to blame:
```
WARNING: The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 0 (Success) on X server ":0"
      after 3379 requests (3356 known processed) with 0 events remaining.
Error: Process completed with exit code 1.
```

Someone else also suggested that maybe the test failures could be due to deprecation of other packages like pytest.

**Comment by tlambert03** [comment]
I ran into this recently... was able to fix it by using xvfb-run directly, instead of using pytest xvfb.  Kind of an annoying fix though.  The problem seems to be caused by windows not being closed, so an alternative might be to have a post test step that makes sure any remaining windows have been closed, but that would take a little testing too

**Comment by jni** [comment]
I'll also note that Grzegorz ran into into this recently. Is it surprising that this doesn't happen in the main repo?

**Comment by jni** [comment]
xref https://napari.zulipchat.com/#narrow/stream/215289-release/topic/0.2E4.2E8/near/237780948

**Comment by tlambert03** [comment]
> Is it surprising that this doesn't happen in the main repo?

Less so, because the make_napari_viewer fixture tries to close all viewers... so the chance for a lingering open window is lower

**Comment by melissawm** [comment]
I believe this is not relevant anymore - please reopen otherwise.
