### ISSUE TITLE
Link to videos of napari talks and tutorials available on the web

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari.github.io#135]
I think it would be good to have a page to put the links to videos of napari talks elsewhere. There's starting to be quite the list. Here is a (very incomplete) list of napari talks & tutorials previously given.

In reverse chronological order...

TALKS
- [ ] Nick Sofroniew — napari: a fast, interactive, multi-dimensional image viewer — BIDS ImageXD 2021 https://www.youtube.com/watch?v=66m8qtOQehs
- [ ] Talley Lambert | napari | Life science lightning talk | Dask Summit 2021 https://www.youtube.com/watch?v=YrQzAMdLU6c&list=PLJ0vO2F_f6OBAY6hjRHM_mIQ9yh32mWr0&index=4
- [ ] napari: an n-dimensional image viewer in Python (Vis2021) Juan Nunez-Iglesias https://www.youtube.com/watch?v=VXdFOcBCto4
- [ ] napari, a fast n dimensional array viewer for scientifc Python | Juan Nunez-Iglesias | SciPy JP 2020 https://www.youtube.com/watch?v=9_Zo2sR75To
- [ ] Kira Evans — ImageXD 2019: Napari: multi-dimensional image visualization in Python https://www.youtube.com/watch?v=L6flM3PYI0Q

TUTORIALS
- [ ] The I2K napari tutorial (I don't think the recording is up online, maybe we could follow up with the organisers?)
- [ ] Multi-dimensional image visualization in Python using napari [NEUBIAS Academy@Home] webinar 2020 https://www.youtube.com/watch?v=VgvDSq5aCDQ

**Comment by GenevieveBuckley** [comment]
Also, Talley gave a great talk at the CZI Imaging Scientists meeting in 2021

* April 2021 - *napari: n-dimensional data viewer in python*
  * [Watch it here](https://www.youtube.com/watch?v=rOO6tK7z6yk) (25 minute video)
  * Presented by Talley Lambert at the CZI Imaging Scientists meeting 2021

**Comment by GenevieveBuckley** [comment]
Also, the SciPy 2021 workshop tutorial happened since I last wrote this list

* June 2021, Bioimage analysis fundamentals in Python workshop at [SciPy 2021](https://www.scipy2021.scipy.org/)
  * [Watch it here](https://www.youtube.com/watch?v=kXdy_Tp12zA) (2 hour and 20 minute video)
  * [Workshop materials available here](https://github.com/sofroniewn/tutorial-scipy2021-bioimage-analysis-fundamentals)

**Comment by alisterburt** [comment]
@kevinyamauchi and I have given a couple of workshops recently and put together a small jupyter-book site https://github.com/alisterburt/napari-workshops currently living at https://alisterburt.github.io/napari-workshops/home.html with the content... I think the idea is that we centralise this onto the napari org account soon but we're figuring some infrastructural stuff before we do that, namely:
- the [remove-cell] incompatibility with screenshots in CI
- we would like downloaded notebooks to be the unexecuted, empty notebook

**Comment by GenevieveBuckley** [comment]
FYI, Nick has set up a napari youtube channel here: https://www.youtube.com/channel/UCbTgw84ew4pxTJ9qu3W2hqg/playlists
