### ISSUE TITLE
Tornado error & Qt warning visible in tutorials documentation

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari.github.io#161]
Currently, there is:
1. A Qt warning, and 
2. A tornado error
... in the first page of the napari tutorials website (so, it's probably on every other page too)

See: 
* Rendered website: https://napari.org/tutorials/
* Jupytext docs used to generate the website: https://github.com/napari/napari.github.io/blob/main/tutorials/index.md

<details>
<summary>Details:</summary>

```
WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-runner'

ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/asyncio/base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 448, in _handle_events
    self._handle_recv()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 477, in _handle_recv
    self._run_callback(callback, msg)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/asyncio/base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/napari/utils/events/event.py:444: RuntimeWarning: coroutine 'get_msg' was never awaited
  for ri, criteria in enumerate((before, after)):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

</details>

![image](https://user-images.githubusercontent.com/30920819/133526103-e3050d88-7708-417c-91e2-b78556d85086.png)

**Comment by melissawm** [comment]
I see these errors when building the documentation for napari locally too.

**Comment by GenevieveBuckley** [comment]
> I see these errors when building the documentation for napari locally too.

That's a good sign, we'll be able to test out fixes locally (much shorter iteration time trying out changes)

**Comment by GenevieveBuckley** [comment]
> "RuntimeError: Cannot run the event loop while another loop is running"

This line makes me wonder if @tlambert03 has an idea about what might have changed recently about how we handle the event loops.

**Comment by tlambert03** [comment]
Looks like that's tornado's asyncio event loop (not ours).  Might need to just try different versions of tornado or other deps.    (It's an indirect dependency, so even though we pin all the rest of our deps, a recent tornado update might have cause this?)

**Comment by GenevieveBuckley** [comment]
Related: I thought the docs build CI was supposed to fail if there were any errors like this. Perhaps this one snuck through because it did eventually display the napari window, so the code snippet did complete.

**Comment by GenevieveBuckley** [comment]
> Looks like that's tornado's asyncio event loop (not ours). Might need to just try different versions of tornado or other deps. (It's an indirect dependency, so even though we pin all the rest of our deps, a recent tornado update might have cause this?)

Hm, the [tornado 6.1 release notes](https://www.tornadoweb.org/en/latest/releases/v6.1.0.html) include this statement:
> Windows support has been improved. Tornado is now compatible with the proactor event loop (which became the default in Python 3.8) by automatically falling back to running a selector in a second thread. This means that it is no longer necessary to explicitly configure a selector event loop, although doing so may improve performance.

Maybe that has something to do with it? I've been assuming based on when Kira pinned the jupyter-book dependencies that tornado 5.1.1 was the version used (it came out in Sept 2018, so seems a safe assumption)

I just spent a bit of time trying to pin tornado to different versions, although pip's dependency resolver was pretty slow/unhappy with it so I didin't get very far.

**Comment by GenevieveBuckley** [comment]
It looks like we *don't* see this tornado warning on the napari staging site at: https://napari.staging.imaging.cziscience.com/

Is the python environment / tornado version different on the staging site? Justin says you might be a good person to ask about this, @codemonkey800

**Comment by codemonkey800** [comment]
The current version in my conda env is `6.1`. Here's the rest of my packages in case it helps:

<details>
<summary>pip list</summary>

```
Package                       Version
----------------------------- ------------
alabaster                     0.7.12
anyio                         3.3.0
appdirs                       1.4.4
appnope                       0.1.2
argon2-cffi                   20.1.0
attrs                         20.3.0
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.9.3
bleach                        4.1.0
cachey                        0.2.1
certifi                       2021.5.30
cffi                          1.14.6
charset-normalizer            2.0.4
click                         8.0.1
cloudpickle                   1.6.0
colorama                      0.4.4
cycler                        0.10.0
dask                          2021.8.1
debugpy                       1.4.1
decorator                     5.0.9
defusedxml                    0.7.1
docstring-parser              0.10
docutils                      0.16
entrypoints                   0.3
freetype-py                   2.2.0
fsspec                        2021.7.0
furo                          2021.6.18b36
ghp-import                    2.0.1
gitdb                         4.0.7
GitPython                     3.1.18
greenlet                      1.1.1
HeapDict                      1.0.1
hsluv                         5.0.2
idna                          3.2
imageio                       2.9.0
imagesize                     1.2.0
importlib-metadata            4.7.1
iniconfig                     1.1.1
ipykernel                     6.2.0
ipython                       7.26.0
ipython-genutils              0.2.0
ipywidgets                    7.6.3
jedi                          0.18.0
Jinja2                        3.0.1
jsonschema                    3.2.0
jupyter-book                  0.10.2
jupyter-cache                 0.4.3
jupyter-client                7.0.1
jupyter-core                  4.7.1
jupyter-server                1.10.2
jupyter-server-mathjax        0.2.3
jupyter-sphinx                0.3.2
jupyterbook-latex             0.2.0
jupyterlab-widgets            1.0.0
jupytext                      1.10.3
kiwisolver                    1.3.1
latexcodec                    2.0.1
linkify-it-py                 1.0.1
locket                        0.2.1
magicgui                      0.2.10
markdown-it-py                0.6.2
MarkupSafe                    2.0.1
matplotlib                    3.4.3
matplotlib-inline             0.1.2
mdit-py-plugins               0.2.6
mistune                       0.8.4
myst-nb                       0.12.3
myst-parser                   0.13.7
napari                        0.4.10
napari-console                0.0.3
napari-plugin-engine          0.1.9
napari-svg                    0.1.5
nbclient                      0.5.4
nbconvert                     5.6.1
nbdime                        3.1.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
nested-lookup                 0.2.22
networkx                      2.6.2
notebook                      6.4.3
numpy                         1.21.2
numpydoc                      1.1.0
packaging                     21.0
pandocfilters                 1.4.3
parso                         0.8.2
partd                         1.2.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.3.1
Pint                          0.17
pip                           21.2.4
pluggy                        0.13.1
pooch                         1.5.1
prometheus-client             0.11.0
prompt-toolkit                3.0.20
psutil                        5.8.0
ptyprocess                    0.7.0
py                            1.10.0
pybtex                        0.24.0
pybtex-docutils               1.0.1
pycparser                     2.20
pydantic                      1.8.2
pydata-sphinx-theme           0.6.3
Pygments                      2.10.0
PyOpenGL                      3.1.5
pyparsing                     2.4.7
PyQt5                         5.15.4
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.9.0
pyrsistent                    0.18.0
pytest                        6.2.4
pytest-qt                     4.0.2
python-dateutil               2.8.2
pytz                          2021.1
PyWavelets                    1.1.1
PyYAML                        5.4.1
pyzmq                         22.2.1
qtconsole                     5.1.1
QtPy                          1.10.0
requests                      2.26.0
requests-unixsocket           0.2.0
scikit-image                  0.18.3
scipy                         1.7.1
Send2Trash                    1.8.0
setuptools                    57.4.0
six                           1.16.0
smmap                         4.0.0
sniffio                       1.2.0
snowballstemmer               2.1.0
soupsieve                     2.2.1
Sphinx                        3.5.4
sphinx-autodoc-typehints      1.11.0
sphinx-book-theme             0.1.3
sphinx-comments               0.0.3
sphinx-copybutton             0.4.0
sphinx-panels                 0.5.2
sphinx-thebe                  0.0.10
sphinx-togglebutton           0.2.3
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-bibtex          2.1.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.23
terminado                     0.11.1
testpath                      0.5.0
tifffile                      2021.8.8
toml                          0.10.2
toolz                         0.11.1
tornado                       6.1
tqdm                          4.62.2
traitlets                     5.0.5
typing-extensions             3.10.0.0
uc-micro-py                   1.0.1
urllib3                       1.26.6
vispy                         0.8.0
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.2.1
wheel                         0.37.0
widgetsnbextension            3.5.1
wrapt                         1.12.1
zipp                          3.5.0
```
</details>



> I see these errors when building the documentation for napari locally too.

Interestingly, I don't see the errors when building the documentation locally 🤔

**Comment by GenevieveBuckley** [comment]
> The current version in my conda env is 6.1

Is that what's being used for the staging site, or just your local environment?

Also, what python version are you using? (I've been using python 3.8, no real reason why)

**Comment by codemonkey800** [comment]
> > The current version in my conda env is 6.1
> 
> Is that what's being used for the staging site, or just your local environment?
> 
> Also, what python version are you using? (I've been using python 3.8, no real reason why)

I'm using Python `3.9.6`, but the deployment workflow uses `3.8`: 
https://github.com/napari/napari.github.io/blob/bd4bd0b86261ca610dbc43a09ef926e5c1697404/.github/workflows/deploy.yml#L21-L23

**Comment by GenevieveBuckley** [comment]
Well, I don't think this has anything to do with the version of python chosen - I'm getting the same errors with python 3.9 as I did with python 3.8

The better question is, why does @codemonkey800 *not* see those errors in his local environment? I don't see anything obviously wrong/different about [that list](https://github.com/napari/napari.github.io/issues/161#issuecomment-925954108)

**Comment by Carreau** [comment]
If we can hide some code, you can try to install nest_asyncio, which will silence these error but might have unattended consequences WRT race conditions.

**Comment by GenevieveBuckley** [comment]
> If we can hide some code, you can try to install nest_asyncio, which will silence these error but might have unattended consequences WRT race conditions.

That seems worrying, I'm not sure we'd want to do that if there's a decent chance of that happening

**Comment by Carreau** [comment]
> That seems worrying, I'm not sure we'd want to do that if there's a decent chance of that happening

it sort of depends whether the two loops interacts. So really you want to know what the outer loop does and what the inner loop does. If they are like completely independant (say one if pytest running one to be able to execute async functions just in case and the other is Jupyter), then it should be fine.

Here we can see the inner is Jupyter, but I'm unsure what the outer one is.

**Comment by melissawm** [comment]
As far as I can tell, the tornado errors have all been solved, so this can be closed.
