### ISSUE TITLE
Error messages at https://napari.org/tutorials/

### ISSUE THREAD

**Issue by kolibril13** [napari/napari.github.io#178]
Getting to the tutorial landing page https://napari.org/tutorials/, one currently sees:
![image](https://user-images.githubusercontent.com/44469195/134986970-febe1905-3ffa-4eae-9da3-316fbe7bc880.png)
I guess there is a bug somewhere.

And just some ideas:
I don't know what framework you use for rendering the docs, but I have made wonderful experiences with readthedocs where users can see different doc versions from different releases:
![image](https://user-images.githubusercontent.com/44469195/134987277-74e984f0-1f96-4b5a-8655-6958127f50c7.png)
One can even see docs from pull requests that are build at readthedocs servers with sphinx.
And with the plugin [nbsphinx](https://nbsphinx.readthedocs.io/en/0.8.6/index.html), one only has to write and commit some Jupyter notebooks, that are then automatically rendered to web-page tutorials.
Probably you are using other tools that are not compatible with that workflow, but maybe it might be useful.

**Comment by tlambert03** [comment]
thanks for reporting!  this is currently being tracked and looked into in https://github.com/napari/napari.github.io/issues/161.  I'm going to close this to keep the conversation in one place
