### ISSUE TITLE
Documentation: review and fix typos/broken links

### ISSUE THREAD

**Issue by melissawm** [napari/napari.github.io#194]
Hi folks,

At the last Documentation working group meeting we talked about checking a few documents for typos, inconsistencies and broken links. A few pages will need changing due to the Docs reorganization work (see #176), but the following are likely to stay the same, and so can be worked on. 

- [ ] [napari viewer tutorial](https://napari.org/tutorials/fundamentals/viewer.html)
- [ ] [Annotating segmentation with text and bounding boxes](https://napari.org/tutorials/applications/annotate_segmentation.html)
- [ ] [Annotating videos with napari](https://napari.org/tutorials/applications/annotate_points.html)
- [ ] [Using Dask and napari to process & view large datasets](https://napari.org/tutorials/applications/dask.html)
- [ ] [Single cell tracking with napari](https://napari.org/tutorials/applications/cell_tracking.html)
- [ ] [An introduction to the event loop in napari](https://napari.org/guides/stable/event_loop.html#intro-to-event-loop)
- [ ] [Asynchronous rendering](https://napari.org/guides/stable/rendering.html)
- [ ] [Rendering in napari](https://napari.org/guides/stable/rendering-explanation.html)
- [ ] [Creating a napari plugin](https://napari.org/plugins/stable/for_plugin_developers.html#plugins-for-plugin-developers)
- [ ] [napari hook specification reference](https://napari.org/plugins/stable/hook_specifications.html)
- [ ] [Finding and installing a napari plugin](https://napari.org/plugins/stable/find-and-install-plugin.html)
- [ ] [napari ImageJ how-to guide](https://napari.org/tutorials/applications/napari_imageJ.html)

**Comment by GenevieveBuckley** [comment]
https://github.com/napari/napari.github.io/pull/185 should be able to address broken links (it appears that we don't currently have any, but we'd like the check to be run on a regular schedule)

**Comment by psobolewskiPhD** [comment]
I'm going to close this. A lot of those docs have been updated and this is better handled on napari/docs now.
