### ISSUE TITLE
napari.org UI Copy with duplicate bullet point

### ISSUE THREAD

**Issue by neuromusic** [napari/napari.github.io#255]
*from October 2021 pre-launch bug bash*

**Created by**: Kevin Lai

## Description 

In https://napari.staging.imaging.cziscience.com/community/index.html, under the "Community" and "Developer Resources", "Roadmap", "release note" section, there is an UI Copy bug where the bullet point is duplicated

## Info

**Bug source**: 1400px

**Browser**: Chrome

**PR**: *none*

## Attachments

https://dl.airtable.com/.attachments/6698ef25e856d55dae707a26e0e18e4a/4fc525f2/ScreenShot2021-09-22at1.15.04PM.png

**Comment by GenevieveBuckley** [comment]
I don't see this bug on [the website page](https://napari.staging.imaging.cziscience.com/community/index.html) today, using either Firefox or Chrome.

![image](https://user-images.githubusercontent.com/30920819/137422591-16520cf2-8df8-4b18-a2fb-464a779fd857.png)

Can anyone else reproduce this issue, or can this be closed?

**Comment by neuromusic** [comment]
@GenevieveBuckley I think you're right... it looks like this was fixed with content changes on staging.
