### ISSUE TITLE
Headline content for admonitions should be consistent

### ISSUE THREAD

**Issue by neuromusic** [napari/napari.github.io#258]
*from October 2021 pre-launch bug bash*

**Created by**: Lia

## Description 

Sometimes the admonitions have a custom title (the purple one on the home page) and sometimes they use the default admonition "type" as the headline (yellow "Important" one on home page). Ideally we would decide which we prefer and be consistent in the content choices.

## Info

**Bug source**: *unknown*

**Browser**: *unknown*

**PR**: *none*

## Attachments

https://dl.airtable.com/.attachments/054ab9fb8e395f8f0612bd474ed04f69/5a0764c6/ScreenShot2021-09-22at2_35_45PM.png

**Comment by psobolewskiPhD** [comment]
The color comes from the type. I think we can close as it's pretty consistent now. Yellow is warning Note is cyan.
If we want to revisit this, this is probably best served for https://github.com/napari/napari-sphinx-theme
