### ISSUE TITLE
missing links in homepage 2nd and 3rd paragraph

### ISSUE THREAD

**Issue by neuromusic** [napari/napari.github.io#263]
*from October 2021 pre-launch bug bash*

**Created by**: lucy

## Description 

"this repository" and "tutorials" could/should have links to github and tutorials respectively

## Info

**Bug source**: *unknown*

**Browser**: chrome

**PR**: *none*

## Attachments

https://dl.airtable.com/.attachments/f1797ddc99787c975e423e671964c9bb/056bdcb6/ScreenShot2021-09-22at3_49_34PM.png

**Comment by GenevieveBuckley** [comment]
Looks like the links to the tutorials have already been added. I've added links to https://github.com/napari/napari wherever the README says "this repository" in https://github.com/napari/napari/pull/3484
