### ISSUE TITLE
embedded calendar on napari.org not showing in local time

### ISSUE THREAD

**Issue by alisterburt** [napari/napari.github.io#274]
## 🐛 Bug

the embedded calendar at https://napari.org/community/team.html#meeting-schedule used to show me the meeting in my local timezone but it's now showing up in pacific

![image](https://user-images.githubusercontent.com/7307488/134183572-4261b3be-0301-4fac-9f46-1f60c7238928.png)

When I originally put the link on I removed time zone info, will check whether someone mistakely left it on when updating the site

**Comment by GenevieveBuckley** [comment]
There is a discussion about replacing the embedded google calendar with something more functional going on here: https://github.com/napari/napari.github.io/issues/271

**Comment by neuromusic** [comment]
thanks @GenevieveBuckley !! is it possible to move this issue to the other repo? it looks like Github supports this, but I don't think I have the right permissions? https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by Carreau** [comment]
Here is a quick workaround we used on jupyter.org. 

https://github.com/jupyter/jupyter.github.io/pull/419

(though I agree changing to react-google-calendar would be great)
