### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by js3711** [napari/napari.github.io#31]
Great work, thanks for your effots!  I'm not sure if it fits within your plans for napari but it would be great to display multiple images at specified x-y-z points utilizing the gpu.

It would be great to customize ![embedding projector](https://projector.tensorflow.org/)-like visualizations.

**Comment by sofroniewn** [comment]
@js3711 I'm afraid I cannot see your linked image, the link is broken.

As for multiple images at different x-y-z points, you should be able to do this by adding each of the images as different layers and they using the `translate` property of the layer to shift it to the right position. This may be a little clunky right now, but curious if that works for you
