### ISSUE TITLE
Non-hidden "nbscreenshot(viewer)"

### ISSUE THREAD

**Issue by Carreau** [napari/napari.github.io#337]
In https://napari.org/tutorials/fundamentals/viewer.html, you can see that the `nbscreenshot(viewer)` code is visible, but it's result is not :

<img width="873" alt="Screen Shot 2022-01-26 at 11 55 26" src="https://user-images.githubusercontent.com/335567/151150987-8e4ddae3-7910-4bff-ac4b-3a1beaa795f1.png">

Bonus, there should be a CI step that verify that the string`nbscreenshot` is not present in the finel Html ?

**Comment by melissawm** [comment]
This is solved, so I believe we can close - please reopen otherwise.
