### ISSUE TITLE
Click handler highjack modifiers/new tabs.

### ISSUE THREAD

**Issue by Carreau** [napari/napari.github.io#343]
Ctrl/Cmd-click open target link in a new tab on many if not all platform, it looks like napari.org highjack this when the target link is another page on napari.org see example where I unbind a callback on `a.reference.internal` where I both time do Cmd-Click, but the first time the page does not open in a new tab.

https://user-images.githubusercontent.com/335567/154073062-2dde223a-8764-470e-a650-d9ba9540f798.mov

**Comment by psobolewskiPhD** [comment]
I can't reproduce this with Stable or dev docs using Safari.
Going to close. If this is still an issue, then I think it belongs on the theme repo:
https://github.com/napari/napari-sphinx-theme
