### ISSUE TITLE
Google takes users to broken pages

### ISSUE THREAD

**Issue by will-moore** [napari/napari.github.io#353]
The top hit for googling "napari plugins" (https://www.google.com/search?q=napari+plugins)
is https://napari.org/plugins/index.html which looks broken (all static files are 404).

I thought that "the site is temporarily broken" and just kept reading it for a while but then found that I should be looking at https://napari.org/stable/plugins/index.html

**Comment by dchudz** [comment]
I think this is fixed now.

`https://napari.org/plugins/index.html` redirects to `https://napari.org/stable/plugins/index.html`.

**Comment by jni** [comment]
Yay! Thanks For the report @will-moore, for the update @dchudz, and for the fix @melissawm!
