### ISSUE TITLE
[Search][v0.4.16] Search Results template is broken

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari.github.io#357]
**Steps to Reproduce**
1. Click on Search bar
2. Enter value for search
3. Click on <enter> key
4. Pay attention to Search Results format

**Actual Results**
Seems template is broken

**Expected Results**
Search results should be visible in correct format in screen

Version: 0.4.16

https://user-images.githubusercontent.com/63799148/182213031-a9d60f7d-9efc-491a-9e59-9091c9bf1336.mov

**Comment by psobolewskiPhD** [comment]
@melissawm #367 is merged, but I still see the issue with search on stable (0.4.16). Not sure if the merge alone should have fixed it or something else needs to happen, so just an FYI.
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/76622105/198965982-e632548c-a2e2-489a-932c-34be83904123.png">

**Comment by melissawm** [comment]
Thanks - that should not happen 🤔 I will investigate.
