### ISSUE TITLE
[Navigation] Navigation labels are not displayed correctly

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari.github.io#358]
**Steps to Reproduce**

1. Navigate through page
2. Go to bottom of page and pay attention to navigation labels

**Expected Results**
Navigation labels should be displayed correctly

**Actual Results**
Labels are too close to each other and some times overlapped

This happens for both versions. For v0.4.16 left label is not visible

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/63799148/182218571-509e29bf-5555-4c5f-be23-f29a55bd4f5f.png">

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/63799148/182218657-262d2d99-f190-4ff0-847e-16de4173cc8d.png">

**Comment by melissawm** [comment]
Could this be a browser issue?
<img width="1161" alt="Screen Shot 2022-08-01 at 6 33 05 PM" src="https://user-images.githubusercontent.com/3949932/182250333-7c00ecdd-bb37-401c-a2cf-ca01d2701dae.png">
<img width="1161" alt="Screen Shot 2022-08-01 at 6 32 32 PM" src="https://user-images.githubusercontent.com/3949932/182250340-82770e69-010c-465f-be79-5fa7294e259e.png">
<img width="1161" alt="Screen Shot 2022-08-01 at 6 34 56 PM" src="https://user-images.githubusercontent.com/3949932/182250449-4dad206e-b690-4410-bd9f-a89e4bf6503e.png">

**Comment by psobolewskiPhD** [comment]
I noted this too in Safari.
With the new theme: https://github.com/napari/napari-sphinx-theme/pull/134
this is now fixed:
![image](https://github.com/napari/napari.github.io/assets/76622105/672e2995-353f-4d01-9303-6cd7a6994e35)
Obviously the issue will persist on older versions of the site, but I think we can close this.
