### ISSUE TITLE
Examples Gallery listing repeated multiple times (Safari) 

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari.github.io#361]
On Safari (both my 12.4 macOS and my 15.5 iOS) I get the listing of Gallery examples repeated like 3x, so it's like 5+ screenfuls of scrolling to actually see the example.
See:
https://napari.org/stable/gallery/set_colormaps.html
It's hard to show in screenshots, but here you can see the scrollbar position and the colormaps example selected:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/76622105/184503807-e3d7f44d-7c3c-4f33-a1a7-5512edccec50.png">
And here you can see the same example repeated (note scrollbar is now 1/2 down the screen):
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/76622105/184503843-5bb2dc3a-c696-48f2-bef9-531d315f727f.png">
And here we go again, at the bottom where one can finally see the example:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/76622105/184503862-f3eba4a7-1f3f-4dd3-9199-4b25a5f7f41a.png">

**Comment by melissawm** [comment]
Thanks @psobolewskiPhD - not sure when this behavior started. napari/napari#4936 should solve it for the devdocs, and I am fixing this on the stable docs next.
