### ISSUE TITLE
[How to install napari][v0.4.16] Blue boxes are not showing content and do not match with v0.4.15

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari.github.io#363]
Steps to Reproduce

1. Go to Getting started -> How to install napari on your machine
2. Navigate to Install as Python package (recommended) section
3. Pay attention to blue boxes

Actual Results
They seem empty until you click on them

Expected Results
They shouldn't look empty or should be collapsed

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/63799148/192856914-cc96f7e4-8c51-4539-95de-d6b62e4d793e.png">

**Comment by melissawm** [comment]
Thanks @lauramarcos - this is the same as napari/napari-sphinx-theme#99 , I'll continue working on that PR.

**Comment by psobolewskiPhD** [comment]
This has been fixed. Stable docs:
![image](https://github.com/napari/napari.github.io/assets/76622105/e086d757-05e1-42d3-8446-3277c40df0d3)
