### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari.github.io#364]
Steps to Reproduce:

1. Go to Annotation -> Annotating videos with napari
2. Navigate to Loading the video section
3. Click on "this" link

Actual Result
404 File not found error

Expected Results
Page should opened as expected

<img width="859" alt="image" src="https://user-images.githubusercontent.com/63799148/192866640-481a6e9a-e276-46bd-93e4-284fbaec7144.png">

Link#2

1. Go to napari tutorials -> Segmentation -> Annotating segmentation with text and bounding boxes
2. Click on "object detection with neural networks"

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/63799148/193112882-4cd9cf73-78d9-4943-89be-5828cd99ccdb.png">

Link napari/napari#3

1. Go to Plugins -> Contributions Guide
2. Navigate to Reader example/Writer example/Widget example/Sample Data section
3. Click on  napari-plugin-engine
4. Click on "hook specification" link

<img width="778" alt="image" src="https://user-images.githubusercontent.com/63799148/195193434-377e7ae7-f92c-41c4-ab99-899d7fa8e7e0.png">

Link napari/napari#4 

1. Go to Plugins -> Best Practices
2. Navigate to How to check test coverage? section
3. Click on "exempt specific lines"

<img width="579" alt="image" src="https://user-images.githubusercontent.com/63799148/195195536-93b1cbb9-e1a8-440d-b396-a6c83e0498bd.png">

**Comment by Czaki** [comment]
The proper issue for napari repository: https://github.com/napari/docs/issues/439

This PR https://github.com/napari/napari/pull/5008 introduce a tool for checking links and fixing part of them.
