### ISSUE TITLE
[4.16][Footer] Footer links disappear when hovering on them

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari.github.io#368]
Steps to Reproduce

1. Go to footer
2. Hover on links
3. Pay attention to links

Actual results
Links disappear when hovering on them

Expected Results
Footer links should change to light blue

https://user-images.githubusercontent.com/63799148/194910476-59677b88-738f-4c5b-bf72-f7b2f389e1c6.mov

**Comment by melissawm** [comment]
Hi @lauramarcos - I believe #367 should fix this.

**Comment by psobolewskiPhD** [comment]
This has been fixed. It's fine on Stable.
