### ISSUE TITLE
[Contributions Reference] Right menu is in bold when it shouldn't

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari.github.io#369]
Steps to Reproduce

Go to Plugins -> Contributions Reference
Pay attention to right menu
Actual Results
Menu is in bold when it should have no format so when it is clicked then it changes to bold format

Expected Results
Menu with no format

![image](https://user-images.githubusercontent.com/63799148/195192672-f63b738d-9f8c-4959-8619-ea75cbd34d4f.png)

![image](https://user-images.githubusercontent.com/63799148/195192701-0ce53fd7-2901-416a-8365-21c05680358a.png)

**Comment by lauramarcos** [comment]
Steps to Reproduce

1. Go to Plugins -> Contributions Reference
2. Pay attention to right menu

Actual Results
Menu is in bold when it should have no format so when it is clicked then it changes to bold format

Expected Results
Menu with no format
<img width="1372" alt="Screen Shot 2022-10-11 at 3 31 08 PM" src="https://user-images.githubusercontent.com/63799148/195192444-5cb5799c-eec1-4cfa-ae5b-1440c9edc2fd.png">

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/63799148/195192474-83be67aa-8a33-4d75-893c-9b7a932812c9.png">

**Comment by melissawm** [comment]
I believe this is due to the code formatting being applied to those titles - see for example https://github.com/napari/npe2/blob/e7fdb2a6b4bd3f3d570ef43b1c1ac3393dad45e1/_docs/templates/_npe2_contributions.md.jinja#L22

**Comment by psobolewskiPhD** [comment]
Here's the latest with new theme:
<img width="309" alt="image" src="https://github.com/napari/napari.github.io/assets/76622105/6191dbc0-94c4-4835-95c4-92c6f2178a87">
The right menu is formatted like the other API/code docs. And which one you're looking at is marked on the side.
To me, this is sufficient to indicate which one is being read.
I'd vote to close this.
