### ISSUE TITLE
[Meeting Schedule] Calendar is broken

### ISSUE THREAD

**Issue by lmarcos** [napari/napari.github.io#374]
## 🐛 Bug

Calendar page is broken

## To Reproduce

1. Go to Community -> Meeting Schedule
2. Pay attention to calendar

## Expected behavior

Calendar is overlapping text underneath

## Environment

This is affecting versions 4..16 and 4.17 - MAC 13.0 Safari 16.1

<img width="1638" alt="image" src="https://user-images.githubusercontent.com/7291920/200074999-36a2a07d-1c62-49c9-8d22-33764860e66d.png">

**Comment by Czaki** [comment]
On Ubuntu Firefox it works. Could you provide more details like OS and Browser?

**Comment by lauramarcos** [comment]
MAC 13.0 Safari 16.1 @Czaki

**Comment by melissawm** [comment]
Is this related to napari/napari#371 or napari/napari#358?

**Comment by lauramarcos** [comment]
@melissawm this is related to https://github.com/napari/napari.github.io/issues/371

**Comment by melissawm** [comment]
Ok - now that 0.4.17 is stable, the calendar appears there correctly: https://napari.org/stable/community/meeting_schedule.html

It will still be broken for 0.4.16, though, because I haven't backported the napari-sphinx-theme to that version of the docs. Do we want to go back and fix that too?

**Comment by psobolewskiPhD** [comment]
IMO someone—like me—looking for the meeting calendar won't be poking around old versions? So it's not so crucial? Maybe better to implement a banner that informs the version is out-dated—I thought there was an issue for this, but can't find anywhere.

**Comment by melissawm** [comment]
The discussion on the warning banner for the old docs is here https://github.com/napari/docs/issues/82

I just updated with the latest from PyData Sphinx theme.

**Comment by psobolewskiPhD** [comment]
So the 0.4.18 stable docs have the jumbled calendar again.
`dev` looks fine, as does 0.4.17
0.4.16 is broken as expected, but fine.
Any ideas @melissawm ? I assume something was missed in the porting of stuff *back* to napari/napari for the release.

**Comment by melissawm** [comment]
Sorry yes, I will try to fix this soon

**Comment by melissawm** [comment]
Fixed by #389
