### ISSUE TITLE
Version switcher drop-down box label and arrow is inconsistent

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari.github.io#377]
When choosing versions on napari.org, the drop-down box label and presence of the arrow is inconsistent. Some versions change names entirely from `version_switcher.json` (e.g. `0.5.0 (development)` becomes `version latest`), some get a `version` prefix (e.g. `0.4.16`), while all other versions just get the version number (`0.4.17`) with no arrow.

https://user-images.githubusercontent.com/2608297/201725612-7bbcf0d5-9c45-43f6-b620-0dc38ff77d1a.mp4

Also, when I originally go to napari.org, I see a flash from `version 0.4.17` to `0.4.17`. I assume that's the redirect?

**Comment by melissawm** [comment]
I will investigate - I suspect this may be due to the pages being built with previous versions of napari-sphinx-theme (which means previous versions of pydata-sphinx-theme) and may present different behavior. In any case they should be fixed, so I'll take a look. Thanks!

**Comment by psobolewskiPhD** [comment]
As an update, the arrow -- which makes it more clear that there is a menu there -- appears with `latest` and `0.4.16` but not the other versions. Also, super minor, 0.4.16 is the only other one (than latest) that has `version` prepended. ). 0.4.17 and 0.4.15 just have the number.
I think having the arrow show on `stable` would be nice, because it does help make it clear there is a menu there to click.

**Comment by psobolewskiPhD** [comment]
Update for the new theme https://github.com/napari/napari-sphinx-theme/pull/134
The latest version (which uses the theme) does have the arrow. 
<img width="147" alt="image" src="https://github.com/napari/napari.github.io/assets/76622105/434f6a36-b160-4f47-b277-41ff17295087">

I agree that having the arrow there is a better visual indicator that the version can be changed...
Stable doesn't show it -- I guess fixing it by patching the deployment here is a possibility? 

@melissawm I think we should close this here and open an issue on the theme to make sure that the arrow shows up for Stable once we release with the new theme (and then we ignore the issue on the other versions). How does that sound?

**Comment by melissawm** [comment]
Ok, so this is fixed for stable and latest, but not <= 0.4.18. Do we want to backport the arrow?

**Comment by psobolewskiPhD** [comment]
> Ok, so this is fixed for stable and latest, but not <= 0.4.18. Do we want to backport the arrow?

IMO no, 0.4.18 clearly looks different ie. has a different theme so there should be no expectation of consistency. It's not worth any effort at this point IMO.
The only question is what will 0.4.19 (current stable) look like after 0.5.0.
If it will have the arrow like currently, then I think we close this.

**Comment by melissawm** [comment]
We can leave this open to check, but I don't see why not - the missing arrow was the result of the old theme, not any changes that may occur after deployment.
