### ISSUE TITLE
[Safari 16.4, macOS] Spinning video on homepage, stable docs only

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari.github.io#387]
Stable (0.4.18) napari.org:
<img width="776" alt="image" src="https://github.com/napari/napari.github.io/assets/76622105/320b3e38-37f2-483a-8b3d-ec3e585b6133">
Spins for >30 min and never loads the video.
What's odd, is `latest` works immediately basically:
<img width="870" alt="image" src="https://github.com/napari/napari.github.io/assets/76622105/b633aaca-9d9f-4761-9dae-1ec0b27560ed">

**Comment by jni** [comment]
(a) I can reproduce
(b) that is indeed bizarre because I just checked and the html around the video element is indeed identical! 🤯 So some other js or *something* must be breaking the video tag for safari on the main page... Gah!

**Comment by jni** [comment]
Here's the issue:

https://github.com/napari/napari.github.io/blob/gh-pages/0.4.18/_static/images/tribolium.webm

the webm is still the lfs pointer, not the file.

**Comment by jni** [comment]
should I just push the file?

**Comment by jni** [comment]
On dev the file is there: https://github.com/napari/napari.github.io/blob/gh-pages/dev/_static/images/tribolium.webm

**Comment by melissawm** [comment]
Shoot, I though I had fixed every LFS thing, it's interesting that this didn't show up when I queried the local LFS files. Here's a fix: https://github.com/napari/napari.github.io/pull/388
